site_name: "Road to GPT"

theme:
  name: material
  icon:
    logo: octicons/ai-model-16
    admonition:
      note: material/alert-circle
      warning: material/alert
  favicon: assets/images/favicon.png  # Optional favicon
  font:
    text: Poppins

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: indigo

  features:
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.suggest

nav:
  - Main: index.md
  - Backpropagation:
    - Micrograd/index.md
  - Language Model-1:
    - Makemore-part1/index.md
  - Language Model-2:
    - Makemore-part2/index.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/custom.css

extra:
  social:
    - icon: material/web
      link: https://muhammedshah.com
    - icon: simple/linkedin
      link: https://linkedin.com/muhammedshah
    - icon: simple/github
      link: https://github.com/muzzammilshah
  # generator: false

plugins:
  - search

copyright: Copyright &copy; 2024 Muhammed Muzzammil Shah