site_name: "Road to GPT"

theme:
  name: material
  icon:
    logo: octicons/ai-model-16
    admonition:
      note: material/pencil-circle
      warning: material/alert
      info: material/alert-circle
  favicon: assets/images/favicon.png
  font:
    text: Poppins

  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: blue

  features:
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.suggest

nav:
  - Main: index.md
  - Backpropagation:
    - Micrograd: Micrograd/index.md
    - Lecture Notes:
      - Master Notes: Micrograd/notes/A-main-video-lecture-notes.md
      - Micrograd Functionality: Micrograd/notes/micrograd-functionality.md
      - Value Object Creation: Micrograd/notes/value-object-creation.md
      - Crux Node Backpropagation: Micrograd/notes/crux-node-backpropagation.md
      - Neurons Explaination: Micrograd/notes/neurons-explaination.md
      - Expanding tanh and adding more operations: Micrograd/notes/expanding-tanh-and-adding-more-operations.md
      - PyTorch Comparison: Micrograd/notes/pytorch-comparision.md
      - Multi-Layer Perceptron: Micrograd/notes/multi-layer-perceptron.md
    - Notebooks:
      - Derivative Simple Function: Micrograd/notebooks/1-derivative-simple-function.ipynb
      - Derivative Function with Multiple Inputs: Micrograd/notebooks/2-derivative-function-with-multiple-inputs.ipynb
      - Graph Visualisation: Micrograd/notebooks/3_1-graph-visualisation.ipynb
      - Value Object: Micrograd/notebooks/3-value-object.ipynb
      - Manual Backpropagation-0: Micrograd/notebooks/4_0_manual_backpropagation_simpleExpression.ipynb
      - Manual Backpropagation-1: Micrograd/notebooks/4_1_manual_backpropagation_simpleExpression.ipynb
      - Manual Backpropagation-2: Micrograd/notebooks/4_2_manual_backpropagation_simpleExpression.ipynb
      - Optimization Single Step Preview: Micrograd/notebooks/5_optimization_single_step_preview.ipynb
      - Backpropagation Neuron: Micrograd/notebooks/6_0_backpropagation_neuron.ipynb
      - Backpropagation Neuron - Manual Calculation: Micrograd/notebooks/6_1_backpropagation_neuron_manual_calculation.ipynb
      - Backward Function - Each operation: Micrograd/notebooks/7_0_backward_func_each_operation.ipynb
      - Backward Function - Entire Graph: Micrograd/notebooks/7_1_backward_func_entire_graph.ipynb
      - Handing one node used multiple times: Micrograd/notebooks/8_handling_onenode_used_multiple_times.ipynb
      - Expanding tanh into more operations: Micrograd/notebooks/9_expanding_tanh_into_more_operations.ipynb
      - Implementing in PyTorch: Micrograd/notebooks/x10_implementing_in_pytorch.ipynb
      - Creating a MLP: Micrograd/notebooks/x11_creating_a_multi_layer_perceptron.ipynb
      - Creating a Loss function: Micrograd/notebooks/x12_creating_a_loss_function.ipynb
      - Collecting all parameters in Neural Net: Micrograd/notebooks/x13_collecting_all_parameters_in_NN.ipynb
      - Manual Gradient Descent Optimization: Micrograd/notebooks/x14_manual_gradient_descent_optimization.ipynb
  - Language Model-1:
    - Makemore Part 1: Makemore-part1/index.md
    - Set A:
      - Lecture Notes: Makemore-part1/A-main-makemore-part1.md
      - Jupyter Notebook: Makemore-part1/A-Main-Notebook.ipynb
    - Set B:
      - Lecture Notes: Makemore-part1/B-main-makemore-part1.md
      - Jupyter Notebook: Makemore-part1/B-Main-Notebook.ipynb
    - Set C:
      - Lecture Notes: Makemore-part1/C-main-makemore-part1.md
      - Jupyter Notebook: Makemore-part1/C-Main-Notebook.ipynb
  - Language Model-2:
    - Makemore Part 2: Makemore-part2/index.md
    - Set A:
      - Lecture Notes: Makemore-part2/A-main-makemore-part2.md
      - Jupyter Notebook: Makemore-part2/A-main-notebook.ipynb
    - Set B:
      - Lecture Notes: Makemore-part2/B-main-makemore-part2.md
      - Jupyter Notebook: Makemore-part2/B-main-notebook.ipynb
    - Set C:
      - Lecture Notes: Makemore-part2/C-main-makemore-part2.md
      - Jupyter Notebook: Makemore-part2/C-main-notebook.ipynb
  - Language Model-3:
    - Makemore Part 3: Makemore-part3/index.md
    - Set A:
      - Lecture Notes: Makemore-part3/A-main-makemore-part3.md
      - Starter Code: Makemore-part3/executed-starter-code.ipynb
      - Jupyter Notebook: Makemore-part3/A-main-notebook.ipynb
      - Visualization Code: Makemore-part3/visualization-tools.ipynb
  - Language Model-4:
    - Makemore Part 4: Makemore-part4/index.md
    - Set A:
      - Exercise 1: Makemore-part4/exercise-1.ipynb
      - Exercise 2: Makemore-part4/exercise-2.ipynb
      - Exercise 3: Makemore-part4/exercise-3.ipynb
      - Final code: Makemore-part4/final-code.ipynb
  - Language Model-5:
    - Makemore Part 5: Makemore-part5/index.md
    - Notes and Codes:
      - Lecture Notes: Makemore-part5/Main-makemore-part-5.md
      - Jupyter Notebook: Makemore-part5/Main-notebook-part-5.ipynb

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/custom.css

extra:
  social:
    - icon: material/web
      link: https://muhammedshah.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/muhammedshah
    - icon: simple/github
      link: https://github.com/muzzammilshah
  # generator: false

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: true

copyright: Copyright &copy; 2024-2025 Muhammed Muzzammil Shah