name: Deploy MkDocs Site

on:
  push:
    branches:
      - main # Change if your default branch is not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Git user credentials (this resolves Git authentication issues)
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Cache dependencies (optional, but recommended for large builds)
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-jupyter

      - run: mkdocs gh-deploy --force